name: Update issue list on README

on:
  issues:
    types: [opened, closed, reopened, edited]
  workflow_dispatch:

jobs:
  update-issue-list:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rewriteReadme
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '<!-- issueTable -->'
          state: 'open'

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update issue list on README" || echo "Nothing to commit"
          git push