name: Issues to README

on:
  issues:
    types: [opened, edited, closed, reopened]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate issues list
        uses: jaywcjlove/issues-to-md@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: README.md
          state: open
          header: "## 🚧 Backlog\n\nOpen issues:\n"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update issue list on README" || exit 0
          git push
